export const SoundManager = {
  // AudioContext — shared single instance
  _ctx: null,

  // Decoded AudioBuffers keyed by effect name — populated on first touch
  _buffers: {},

  // Track which fetches are in-flight so concurrent calls don't double-fetch
  _loading: {},

  // Flag: has init() been called?
  isInitialized: false,

  // Sound file map — same names as before
  _files: {
    flip: "sounds/card-flip.ogg",
    shuffle: "sounds/card-shuffle.ogg",
    bounty: "sounds/bounty.wav",
    queen: "sounds/queen.wav",
    lucky7: "sounds/lucky7.wav",
    correct: "sounds/correct.mp3",
    incorrect: "sounds/incorrect.wav",
    tie: "sounds/tie.wav",
    hotStreak: "sounds/hot-streak.wav",
    shield: "sounds/shield.wav",
    sabotage: "sounds/sabotage.wav",
    menu: "sounds/menu.wav",
    menuEnd: "sounds/menu-end-game.wav",
    action: "sounds/menu.wav",
    eliminated: "sounds/eliminated.wav",
    win: "sounds/win.wav",
  },

  // Card and avatar images to warm the browser cache on first touch
  _images: [
    "images/Cards/Back.png",
    "images/bg-home.png",
    "images/bg-game.png",
    "images/Avatars/man 1.png",
    "images/Avatars/man 2.png",
    "images/Avatars/man 3.png",
    "images/Avatars/boy 1.png",
    "images/Avatars/boy 2.png",
    "images/Avatars/boy 3.png",
    "images/Avatars/woman 1.png",
    "images/Avatars/woman 2.png",
    "images/Avatars/woman 3.png",
    "images/Avatars/girl 1.png",
    "images/Avatars/girl 2.png",
    "images/Avatars/girl 3.png",
  ],

  // Preload images by creating Image objects so the browser caches them.
  _preloadImages() {
    // 1. Load static images (backgrounds, avatars, card back)
    this._images.forEach(function (src) {
      var img = new Image();
      img.src = src;
    });

    // 2. Dynamically load all 52 cards to prevent animation stuttering on first draw
    const colors = ["Blue", "Yellow", "Red", "Green"];
    const ranks = ["A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"];
    
    colors.forEach(color => {
      ranks.forEach(rank => {
        var img = new Image();
        // Match the exact path structure generated by View.getCardImagePath
        img.src = `images/cards/${color}_${rank}.png`;
      });
    });
  },

  /**
   * Called on the very first user touch/click.
   * 1. Creates and resumes the AudioContext (satisfies mobile autoplay policy).
   * 2. Plays 1 frame of silence to warm the hardware DAC.
   * 3. Fetches and decodes every sound file into memory in parallel.
   * 4. Kicks off image preloading in parallel (fire-and-forget).
   */
  init() {
    if (this.isInitialized) return;
    this.isInitialized = true;

    const AC = window.AudioContext || window.webkitAudioContext;
    if (!AC) {
      console.warn("[SoundManager] Web Audio API not supported.");
      return;
    }

    this._ctx = new AC();

    // Warm the hardware: play 1 frame of silence
    const warmup = this._ctx.createBuffer(1, 1, 22050);
    const src = this._ctx.createBufferSource();
    src.buffer = warmup;
    src.connect(this._ctx.destination);
    src.start(0);

    // Resume if suspended (Safari / Chrome mobile)
    const resume = () => {
      if (this._ctx && this._ctx.state === "suspended") {
        this._ctx.resume();
      }
    };
    resume();
    document.addEventListener("touchstart", resume, {
      passive: true,
      once: true,
    });
    document.addEventListener("pointerdown", resume, {
      passive: true,
      once: true,
    });

    // Decode all sounds into AudioBuffers in parallel
    console.log("[SoundManager] Pre-decoding all sounds...");
    Promise.all(
      Object.entries(this._files).map(([name, url]) =>
        this._fetchAndDecode(name, url),
      ),
    ).then(() => {
      console.log("[SoundManager] All sounds decoded and ready.");
    });

    // Preload images (warms browser cache — fire and forget)
    this._preloadImages();
  },

  // Fetch a sound file, decode it, store in _buffers.
  // Safe to call multiple times — skips if already loaded or loading.
  async _fetchAndDecode(name, url) {
    if (this._buffers[name] || this._loading[name]) return;
    this._loading[name] = true;
    try {
      const response = await fetch(url);
      if (!response.ok) throw new Error("HTTP " + response.status);
      const arrayBuffer = await response.arrayBuffer();
      this._buffers[name] = await this._ctx.decodeAudioData(arrayBuffer);
    } catch (e) {
      console.warn("[SoundManager] Failed to decode " + name + ":", e);
    } finally {
      this._loading[name] = false;
    }
  },

  // Preload images by creating Image objects so the browser caches them.
  _preloadImages() {
    this._images.forEach(function (src) {
      var img = new Image();
      img.src = src;
    });
  },

  // Play a decoded AudioBuffer instantly.
  // Each call creates a new BufferSourceNode — correct Web Audio pattern,
  // allows the same sound to overlap (e.g. rapid card flips).
  play(effect) {
    const isMuted = localStorage.getItem("BOUNTY_MUTED") === "true";
    if (isMuted) return;

    if (!this._ctx) {
      console.warn(
        "[SoundManager] Context not ready for " +
          effect +
          ". Was init() called?",
      );
      return;
    }

    const buffer = this._buffers[effect];

    if (!buffer) {
      // Buffer not decoded yet — attempt a late decode then play
      const url = this._files[effect];
      if (url && !this._loading[effect]) {
        this._fetchAndDecode(effect, url).then(() => this._playBuffer(effect));
      }
      return;
    }

    this._playBuffer(effect);
  },

  // Internal: create a source node and fire immediately.
  _playBuffer(effect) {
    const buffer = this._buffers[effect];
    if (!buffer || !this._ctx) return;

    // If context suspended (tab backgrounded), resume first then retry
    if (this._ctx.state === "suspended") {
      this._ctx.resume().then(() => this._playBuffer(effect));
      return;
    }

    try {
      const source = this._ctx.createBufferSource();
      source.buffer = buffer;
      source.connect(this._ctx.destination);
      source.start(0);
    } catch (e) {
      console.warn("[SoundManager] Error playing " + effect + ":", e);
    }
  },
};
